<link rel="stylesheet" href="{{ asset('frontend') }}/assets/css/plugins/bootstrap.min.css">
<link rel="stylesheet" href="{{ asset('frontend') }}/assets/css/plugins/aos.css">
<link rel="stylesheet" href="{{ asset('frontend') }}/assets/css/plugins/fontawesome.css">
<link rel="stylesheet" href="{{ asset('frontend') }}/assets/css/plugins/magnific-popup.css">
<link rel="stylesheet" href="{{ asset('frontend') }}/assets/css/plugins/mobile.css">
<link rel="stylesheet" href="{{ asset('frontend') }}/assets/css/plugins/owlcarousel.min.css">
<link rel="stylesheet" href="{{ asset('frontend') }}/assets/css/plugins/sidebar.css">
<link rel="stylesheet" href="{{ asset('frontend') }}/assets/css/plugins/slick-slider.css">
<link rel="stylesheet" href="{{ asset('frontend') }}/assets/css/plugins/nice-select.css">
<link rel="stylesheet" href="{{ asset('frontend') }}/assets/css/main.css">